global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  
  - job_name: "otel_collector"
    static_configs:
    - targets: ["otel:8989"]