version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--enable-feature=remote-write-receiver'
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    command:
      - --collector.otlp.enabled=true
      - --prometheus.query.support-spanmetrics-connector=true
    ports:
      - "16686:16686"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    depends_on:
      - prometheus

  otel:
    image: otel/opentelemetry-collector-contrib
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./conf/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger

  checkoutapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_SERVICE_NAME=checkout
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
    ports:
      - 9091:9090
    depends_on:
      - otel
  
  paymentapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_SERVICE_NAME=payments
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
    depends_on:
      - otel
