version: '3.8'
services:
  ingressproxy:
    image: opentracing/nginx-opentracing
    container_name: ingressproxy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./conf/ingressproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ingressproxy/jaeger-config.json:/etc/jaeger-config.json
      - ./conf/ingressproxy/var/log/nginx:/var/log/nginx/
  
  egressproxy:
    image: opentracing/nginx-opentracing
    container_name: egressproxy
    restart: unless-stopped
    volumes:
      - ./conf/egressproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/egressproxy/jaeger-config.json:/etc/jaeger-config.json
      - ./conf/egressproxy/var/log/nginx:/var/log/nginx/

  checkoutapi:
    container_name: checkoutapi
    build:
      context: ./app
      dockerfile: Dockerfile
      
  paymentapi:
    container_name: paymentapi
    build:
      context: ./app
      dockerfile: Dockerfile

  ingress_exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
    container_name: ingress_exporter
    restart: unless-stopped
    command: -config-file /etc/prometheus/exporterconfig.yaml
    volumes:
      - ./conf/ingressproxy/exporterconfig.yaml:/etc/prometheus/exporterconfig.yaml
      - ./conf/ingressproxy/var/log/nginx:/var/log/nginx/
  
  egress_exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
    container_name: egress_exporter
    restart: unless-stopped
    command: -config-file /etc/prometheus/exporterconfig.yaml
    volumes:
      - ./conf/egressproxy/exporterconfig.yaml:/etc/prometheus/exporterconfig.yaml
      - ./conf/egressproxy/var/log/nginx:/var/log/nginx/
    
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  
  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    container_name: jaeger
    ports:
      - "16686:16686"
